### PR TITLE
Feature initial setup

### LINKED ISSUE #1: [Setup] Make configuration changes for Ionic Framework integration
Problem:
The project require ionic framework integration

Solution:
Make code and file system changes in  the repository to integrate ionic framework

### LINKED ISSUE #2: [InitialSetup]Make configuration changes for angular framework integration
Problem
Angular framework is require  in developing the Frontend of the application

**TODO*
Make code and filesystem changes to integrate angular framework in the repository

### LINKED ISSUE #4: [README] UPDATE README
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by ianakoto**
## Description
Please include a summary of the change and relevant motivation and context. 
Project created with ionic . the chosen framework was angular and the web app was converted to android app using capacitor

List any dependencies that are required for this change.
1. Ionic 
2. Nodejs
3. Android studio

Fixes #(issue number 1) #(issue number 2 )

## How Has This Been Tested?
I built the project and run using android studio for the android app and it worked
I also built the ionic web app and it worked

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Arshir — APPROVED** [review]
This is the general initial setup of the repo with integration of require frameworks and installation of dependencies

**Review by mickeymond — COMMENTED** [review]
Looks Great

**Review by mickeymond — APPROVED** [review]
Great

**Review by Arshir — APPROVED** [review]
Approved

**Review by Deekerubo — APPROVED** [review]

**Pull request merged**
