### PR TITLE
Statistics Page

### LINKED ISSUE #46: [FEATURE] UI Statistics page for displaying graph
This feature implements a UI that enables users to visualize their progress with charts to know their status

### PR DESCRIPTION
**Pull request by ianakoto**
## Description
UI implementation of statistics page to show bar graph of user's time series speed

Fixes #(issue number 46) 

## How Has This Been Tested?
This has been tested in chrome browser 

## Checklist:
- [x ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by linhobs — COMMENTED** [review]
looks good

**Review by linhobs — COMMENTED** [review]
Good

**Review by linhobs — DISMISSED** [review]

**Review by mickeymond — DISMISSED** [review]
Nice

**Review by penbosso — DISMISSED** [review]

**Review by ErnestinaTawiah — APPROVED** [review]
good job

**Review by mickeymond — APPROVED** [review]

**Review by Arshir — APPROVED** [review]
This pull request is approved. This includes both statistics page and achievement page

**Pull request merged**
